### ISSUE TITLE
ResNet seems to accept single-channel inputs only

### ISSUE THREAD

**Issue by tombewley** [tombewley/astrogym#2]
Here's how I'm currently manipulating the observation (oiriginally 100x100x5) to send it to the ResNet - the only way I could get it to produce an output of the correct shape without throwing an error was to give it a single channel only. Does the ResNet class need tweaking a bit?

https://github.com/tombewley/astrogym/blob/fc080da71a9a289bd9785f877d80990d4ceaef57/run_random_policy.py#L13-L16

**Comment by Smith42** [comment]
the linked pull request should fix this
